Mainpage/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('auctions/', include(('auctions.urls', 'auctions'), namespace='auctions')),
    path('Dashboard/', include(('Dashboard.urls', 'auctions'), namespace='Dashboard')),
]

Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Mainpage.urls")),
    path("/auctions/", include("auctions.urls")),
    path('Dashboard/', include('Dashboard.urls')),
]

Mainpage/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

Mainpage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.contrib.auth import authenticate, login ,logout
from django.contrib.auth.models import User

# Create your views here.
def index(request):
    return render(request , 'Mainpage/index.html')

Mainpage/templates/Mainpage/index.html
{% load static %}
<!DOCTYPE html>
<html>


<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Portfolio</title>

  <!-- slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css" />

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,600,700&display=swap" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
</head>

<body>

  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="index.html">
            
            <span>
              Lethabo
            </span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="s-1"> </span>
            <span class="s-2"> </span>
            <span class="s-3"> </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="d-flex ml-auto flex-column flex-lg-row align-items-center">
              <ul class="navbar-nav  ">
                <li class="nav-item active">
                  <a class="nav-link" href="">Home <span class="sr-only">(current)</span></a>
                </li>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->
    <!-- slider section -->
    <section class=" slider_section ">
      <div class="container">
        <div class="row">
          <div class="col-md-6 ">
            <div class="detail_box">
              <h1>
                backend <br>
                Developer <br>
                
              </h1>
              <p>
                I'm a Back-End Developer passionate about creating robust, efficient, and scalable solutions. My expertise in server-side technologies, database architecture, and API development delivers cutting-edge solutions. I'm always up-to-date with industry trends, bringing innovation to every project. I'd love to connect and discuss how I can take your ideas to new heights through back-end development. Thank you for visiting, and I look forward to working with you!
              </p>
            </div>
          </div>
          <!--<div class="col-lg-5 col-md-6 offset-lg-1">
            <div class="img_content">
              <div class="img_container">
                <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <div class="img-box">
                        <img src="{% static 'images/main.jpg' %}" alt="">
                      </div>
                    </div>
                    <div class="carousel-item">
                      <div class="img-box">
                        <img src="{% static 'images/main.jpg' %}" alt="">
                      </div>
                    </div>
                    <div class="carousel-item">
                      <div class="img-box">
                        <img src="{% static 'images/main.jpg' %}" alt="">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>  --> 
        </div>
      </div>
    </section>
    <!-- end slider section -->
  </div>

  <!-- service section -->
  <section class="service_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          Portfolio Projects
        </h2>
        <img src="{% static 'images/plug.png' %}" alt="">
      </div>

      <div class="service_container">
        <a href="{% url 'Dashboard:index' %}">
          <div class="box">
            <div class="img-box">
              <img src="{% static 'images/s1.png' %}" class="img1" alt="">
            </div>
            <div class="detail-box">
              <h5>
                Trading Dashboard
              </h5>
              <p>
                A a live dynamc trading view, to see all your assets
              </p>
            </div>
          </div>
        </a>
        
        <a href="{% url 'auctions:index' %}">
          <div class="box active">
            <div class="img-box">
              <img src="{% static 'images/s2.png' %}" class="img1" alt="">
            </div>
              <div class="detail-box">
                <h5>
                  Auction site
                </h5>
                <p>
                  Dynamic eCommerce site showcasing development expertise.
                </p>
              </div>
          </div>
        </a>
        
        
      </div>
      <!--
      <div class="btn-box">
        <a href="">
          Read More
        </a>
      </div>
      -->
    </div>
  </section>
  <!-- end service section https://api.coingecko.com/api/v3/coins/bitcoin -->

  <!-- about section 
  <section class="about_section layout_padding">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="detail-box">
            <div class="heading_container">
              <h2>
                About Us
              </h2>
              <img src="{% static 'images/plug.png' %}" alt="">
            </div>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
              commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
        <div class="col-md-6">
          <div class="img_container">
            <div class="img-box b1">
              <img src="{% static 'images/about-img1.jpg' %}" alt="" />
            </div>
            <div class="img-box b2">
              <img src="{% static 'images/about-img2.jpg' %}" alt="" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </section> -->
  <!-- end about section -->


  <!-- info section -->

  <section class="info_section layout_padding">
    <div class="container">
      <div class="info_contact">
        <div class="row">
          <div class="col-md-4">
            <a href="">
              <img src="images/location-white.png" alt="">
              <span>
                Based in Cape Town
              </span>
            </a>
          </div>
          <div class="col-md-4">
            <a href="">
              <img src="images/telephone-white.png" alt="">
              <span>
                Call : +27 676393407
              </span>
            </a>
          </div>
          <div class="col-md-4">
            <a href="">
              <img src="images/envelope-white.png" alt="">
              <span>
                Lethabo.codes@gmail.com
              </span>
            </a>
          </div>
        </div>
      </div>
      

    </div>
  </section>

  <!-- end info section -->

  <!-- info section -->
  <section class="info_section layout_padding">
    <div class="container">
      <!-- ... rest of your HTML code ... -->
    </div>
  </section>
  <!-- end info section -->

  <!-- footer section -->
  <footer class="container-fluid footer_section">
    <div class="container">
      <!-- ... rest of your HTML code ... -->
    </div>
  </footer>
  <!-- footer section -->

  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.js' %}"></script>

  <script>
const url = 'https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=zar&days=7&interval=daily';

fetch(url)
  .then(response => {
    if (!response.ok) {
      throw new Error('Network response was not ok');
    }
    return response.json();
  })
  .then(bitcoinData => {
    const prices = bitcoinData.prices;
    if (prices && prices.length > 0) {
      const secondNumbers = prices.map(price => price[1]);
      console.log('Second numbers from prices:', secondNumbers);
    } else {
      console.error('Prices data not available');
    }
  })
  .catch(error => {
    console.error('There was a problem with the fetch operation:', error);
  });



  </script>

</body>

</html>